//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPHotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Authorize
    {
        public int IDuser { get; set; }
        public string LoginUser { get; set; }
        public string PasswordUser { get; set; }
        public Nullable<bool> IsAdmin { get; set; }
        public Nullable<bool> IsManager { get; set; }
    }
}
